### ISSUE TITLE
Training is not coverage

### ISSUE THREAD

**Issue by ducanh841988** [wwjwhen/Watch-Attend-and-Spell-tensorflow-version#3]
I use python 3.7 and TF 1.6
The code has 2 errors:

in model-single-GPU.py line 383, in <lambda>
    lambda: tf.nn.embedding_lookup(wap.embed_matrix, sample_y)
NameError: name 'wap' is not defined

--> I changed wap.embed_matrix to self.embed_matrix

in model-single-GPU.py line 465, in
input_dict = {
			anno:ctx,
			infer_y:next_w,
			alpha_past:next_alpha_past,
			h_pre:next_state,
			if_trainning:training
			}
NameError: name 'anno' is not defined

--> I added global definition for variables
global anno, infer_y, h_pre, alpha_past, if_trainning

Finally, I can run the code, but it is not coverage.
WER and cost in the validation set dose not reduce.
Do you have any suggestion?

Thank you alot.

**Comment by ali171m** [comment]
Hi ducanh841988,
Do you have any progress in training? I am also trying to train WAP framework and stuck at WER and cost in the validation set dose not reduce. Kindly share any tips if you have solved the problem
